[main]
font=JetBrainsMono Nerd Font:size=12
terminal=alacritty
use-bold=yes
#dpi-aware=yes

width=15
lines=5

[colors]
background=000000ff
text=aaaaaaff
selection=000000ff
selection-text=ffffffff
border=000000ff

