$font = "JetBrainsMono Nerd Font Bold"

general {
    no_fade_in = true
    disable_loading_bar = true
}

background {
    monitor = 
    path = screenshot
    blur_passes = 4
    contrast = 0.892
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =

    size = 100, 30

    outline_thickness = 0

    outer_color = rgb(ffffff)
    inner_color = rgb(000000)

    font_color = rgb(ffffff)

    fade_on_empty = false

    placeholder_text =
    fail_text =

    rounding = 0

    position = 0, 10 
    halign = center
    valign = bottom
}

label {
    monitor =

    text = cmd[update:1000] echo -e "$(date +'%H:%M')"

    color = rgb(ffffff)

    font_size = 11
    font_family = $font

    position = 909, 10

    halign = center
    valign = bottom 
}
