alias s="yay -Syu --needed"
alias e="exit"
alias c="clear"
alias conf="nvim ~/.config"
alias hi="sudo env WAYLAND_DISPLAY=$WAYLAND_DISPLAY XDG_SESSION_TYPE=$XDG_SESSION_TYPE XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR hiddify"
